/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package petadoptionconsortium;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Vector;
/**
 *
 * @author Doug
 */
public class AddNewEvent extends javax.swing.JPanel {

    /**
     * Creates new form AddNewEvent
     */
    private Vector eventTypes;
    public static String[][] choices = new String[][] { {"","","",""},{"","","",""},{"","","",""},{"","","",""}};
    public AddNewEvent() {
        eventTypes = new Vector();
        eventTypes.addElement("");
        eventTypes.addElement("Adoption");
        eventTypes.addElement("Fundraising");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        type1 = new javax.swing.JComboBox();
        type2 = new javax.swing.JComboBox();
        type3 = new javax.swing.JComboBox();
        type4 = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        location1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        location2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        location3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        location4 = new javax.swing.JTextArea();
        dateDay2 = new javax.swing.JTextField();
        dateDay3 = new javax.swing.JTextField();
        dateDay4 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        desc1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        desc2 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        desc3 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        desc4 = new javax.swing.JTextArea();
        dateMonth1 = new javax.swing.JTextField();
        dateDay1 = new javax.swing.JTextField();
        dateYear2 = new javax.swing.JTextField();
        dateYear3 = new javax.swing.JTextField();
        dateYear4 = new javax.swing.JTextField();
        dateYear1 = new javax.swing.JTextField();
        dateMonth2 = new javax.swing.JTextField();
        dateMonth3 = new javax.swing.JTextField();
        dateMonth4 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(730, 630));

        jLabel1.setText("Atlanta Pet Adoption Consortium");

        jLabel2.setText("Add New Events for Shelter " + PetAdoptionConsortium.shelterName);

        type1.setModel(new DefaultComboBoxModel(this.eventTypes));

        type2.setModel(new DefaultComboBoxModel(this.eventTypes));

        type3.setModel(new DefaultComboBoxModel(this.eventTypes));

        type4.setModel(new DefaultComboBoxModel(this.eventTypes));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Type");

        jLabel4.setText("Location");

        jLabel5.setText("Date");

        jLabel6.setText("Description");

        location1.setColumns(12);
        location1.setRows(3);
        jScrollPane1.setViewportView(location1);

        location2.setColumns(12);
        location2.setRows(3);
        jScrollPane2.setViewportView(location2);

        location3.setColumns(12);
        location3.setRows(3);
        jScrollPane3.setViewportView(location3);

        location4.setColumns(12);
        location4.setRows(3);
        jScrollPane4.setViewportView(location4);

        dateDay2.setText("DD");
        dateDay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDay2ActionPerformed(evt);
            }
        });

        dateDay3.setText("DD");
        dateDay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDay3ActionPerformed(evt);
            }
        });

        dateDay4.setText("DD");

        desc1.setColumns(17);
        desc1.setRows(3);
        jScrollPane5.setViewportView(desc1);

        desc2.setColumns(15);
        desc2.setRows(3);
        jScrollPane6.setViewportView(desc2);

        desc3.setColumns(17);
        desc3.setRows(3);
        jScrollPane7.setViewportView(desc3);

        desc4.setColumns(17);
        desc4.setRows(3);
        jScrollPane8.setViewportView(desc4);

        dateMonth1.setText("MM");
        dateMonth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateMonth1ActionPerformed(evt);
            }
        });

        dateDay1.setText("DD");
        dateDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDay1ActionPerformed(evt);
            }
        });

        dateYear2.setText("YYYY");
        dateYear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateYear2ActionPerformed(evt);
            }
        });

        dateYear3.setText("YYYY");

        dateYear4.setText("YYYY");

        dateYear1.setText("YYYY");
        dateYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateYear1ActionPerformed(evt);
            }
        });

        dateMonth2.setText("MM");

        dateMonth3.setText("MM");

        dateMonth4.setText("MM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(533, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateYear2)
                                            .addComponent(dateYear1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dateMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dateDay2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dateMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dateDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(dateYear4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dateMonth4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dateDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(dateYear3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dateMonth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dateDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel4)
                                .addGap(133, 133, 133)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(124, 124, 124))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(submitButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dateMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dateDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(type2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dateDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateMonth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateYear3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(type4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateMonth4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateYear4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(submitButton)
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateDay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateDay2ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String typeChoice1 = type1.getSelectedItem().toString();
        String typeChoice2 = type2.getSelectedItem().toString();
        String typeChoice3 = type3.getSelectedItem().toString();
        String typeChoice4 = type4.getSelectedItem().toString();
        String locationChoice1 = location1.getText();
        String locationChoice2 = location2.getText();
        String locationChoice3 = location3.getText();
        String locationChoice4 = location4.getText();
        String dateChoice1 = dateYear1.getText()+"-"+dateMonth1.getText()+"-"+dateDay1.getText();
        String dateChoice2 = dateYear2.getText()+"-"+dateMonth2.getText()+"-"+dateDay1.getText();
        String dateChoice3 = dateYear3.getText()+"-"+dateMonth3.getText()+"-"+dateDay1.getText();
        String dateChoice4 = dateYear4.getText()+"-"+dateMonth4.getText()+"-"+dateDay1.getText();
        String descChoice1 = desc1.getText();
        String descChoice2 = desc2.getText();
        String descChoice3 = desc3.getText();
        String descChoice4 = desc4.getText();
        choices[0] = new String[] {typeChoice1,locationChoice1,dateChoice1,descChoice1};
        choices[1] = new String[] {typeChoice2,locationChoice2,dateChoice2,descChoice2};
        choices[2] = new String[] {typeChoice3,locationChoice3,dateChoice3,descChoice3};
        choices[3] = new String[] {typeChoice4,locationChoice4,dateChoice4,descChoice4};
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.ADD_NEW_EVENT_SUCCESS;
        PetAdoptionConsortium.changeScreen = true;
        //date-location-shelter-type-description
    }//GEN-LAST:event_submitButtonActionPerformed

    private void dateMonth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateMonth1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateMonth1ActionPerformed

    private void dateDay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateDay1ActionPerformed

    private void dateYear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateYear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateYear2ActionPerformed

    private void dateDay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDay3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateDay3ActionPerformed

    private void dateYear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateYear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateYear1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateDay1;
    private javax.swing.JTextField dateDay2;
    private javax.swing.JTextField dateDay3;
    private javax.swing.JTextField dateDay4;
    private javax.swing.JTextField dateMonth1;
    private javax.swing.JTextField dateMonth2;
    private javax.swing.JTextField dateMonth3;
    private javax.swing.JTextField dateMonth4;
    private javax.swing.JTextField dateYear1;
    private javax.swing.JTextField dateYear2;
    private javax.swing.JTextField dateYear3;
    private javax.swing.JTextField dateYear4;
    private javax.swing.JTextArea desc1;
    private javax.swing.JTextArea desc2;
    private javax.swing.JTextArea desc3;
    private javax.swing.JTextArea desc4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea location1;
    private javax.swing.JTextArea location2;
    private javax.swing.JTextArea location3;
    private javax.swing.JTextArea location4;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox type1;
    private javax.swing.JComboBox type2;
    private javax.swing.JComboBox type3;
    private javax.swing.JComboBox type4;
    // End of variables declaration//GEN-END:variables
}
