/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package petadoptionconsortium;

/**
 *
 * @author Doug
 */
public class AddNewDogOrCat extends javax.swing.JPanel {
    public static String dogOrCat = "Dog";
    /**
     * Creates new form AddNewDogOrCat
     */
    public AddNewDogOrCat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addNewDog = new javax.swing.JButton();
        addNewCat = new javax.swing.JButton();
        returnToMenu = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(730, 630));

        jLabel1.setText("Atlanta Pet Adoption Consortium");

        addNewDog.setText("Add New Dog");
        addNewDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDogActionPerformed(evt);
            }
        });

        addNewCat.setText("Add New Cat");
        addNewCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCatActionPerformed(evt);
            }
        });

        returnToMenu.setText("Return to Menu");
        returnToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnToMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(addNewDog)
                                .addGap(202, 202, 202)
                                .addComponent(addNewCat)))
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addNewDog, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewCat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addComponent(returnToMenu)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCatActionPerformed
        dogOrCat = "Cat";
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.ADD_NEW_PET;
        PetAdoptionConsortium.changeScreen = true;
    }//GEN-LAST:event_addNewCatActionPerformed

    private void returnToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenuActionPerformed
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.LOGIN_PANEL;
        PetAdoptionConsortium.changeScreen = true;        // TODO add your handling code here:
    }//GEN-LAST:event_returnToMenuActionPerformed

    private void addNewDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDogActionPerformed
        dogOrCat = "Dog";
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.ADD_NEW_PET;
        PetAdoptionConsortium.changeScreen = true;
    }//GEN-LAST:event_addNewDogActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewCat;
    private javax.swing.JButton addNewDog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton returnToMenu;
    // End of variables declaration//GEN-END:variables
}
