/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package petadoptionconsortium;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import static petadoptionconsortium.AddNewPet.ageChoice;
import static petadoptionconsortium.AddNewPet.breedChoice;
import static petadoptionconsortium.AddNewPet.genderChoice;
import static petadoptionconsortium.AddNewPet.nameChoice;
import static petadoptionconsortium.AddNewPet.petID;
import static petadoptionconsortium.AddNewPet.typeChoice;

/**
 *
 * @author Doug
 */
public class AddNewPetSuccess extends javax.swing.JPanel {

    /**
     * Creates new form AddNewPetSuccess
     */
    public AddNewPetSuccess() {
        
        Connection connection2 = null;
        PreparedStatement pstatement1 = null;
        PreparedStatement pstatement2 = null;
        PreparedStatement pstatement3 = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connection2 = DriverManager.getConnection(PetAdoptionConsortium.CONN_STRING,"root","");
            String insertQuery = new String();
            String prefixQuery = "SET FOREIGN_KEY_CHECKS = 0; \n";

            insertQuery = "INSERT INTO `Pet` (`PetID`, `Age`, `Gender`, `PetName`, `ShelterName`, `ArrivalDate`, `AdopterName`, `AdopterPhone`, `FosterName`, `FosterPhone`, `AdoptionDate`, `FosterDate`, `DogBreed`, `CatBreed`) "
                    + "Values (?,?,?,?,?,Date(Now()),NULL,NULL,NULL,NULL,NULL,NULL,?,?); \n";
            String suffixQuery = "SET FOREIGN_KEY_CHECKS = 1; \n";
            pstatement1 = connection2.prepareStatement(prefixQuery);
            pstatement2 = connection2.prepareStatement(insertQuery);
            pstatement3 = connection2.prepareStatement(suffixQuery);
            
            pstatement2.setString(1, AddNewPet.petID);
            pstatement2.setString(2, AddNewPet.ageChoice);
            pstatement2.setString(3, AddNewPet.genderChoice);
            pstatement2.setString(4, AddNewPet.nameChoice);
            pstatement2.setString(5, PetAdoptionConsortium.shelterName);
            if (AddNewPet.typeChoice.equals("Dog")) {
                pstatement2.setString(6, AddNewPet.breedChoice);
                pstatement2.setString(7, "");
            }
            else if (AddNewPet.typeChoice.equals("Cat")) {
                pstatement2.setString(6,"");
                pstatement2.setString(7, AddNewPet.breedChoice);
            }
            if (AddNewPet.buttonPressed == true) {
                pstatement1.execute();
                pstatement2.executeUpdate();
                pstatement3.execute();
            }
        }
        catch(SQLException sqlException) {
            sqlException.printStackTrace();
            System.exit(1);
        }
        catch(ClassNotFoundException classNotFound) {
            classNotFound.printStackTrace();
            System.exit(1);
        }
        finally {
            try {
                pstatement2.close();
                connection2.close();
            }
            catch(Exception exception) {
                exception.printStackTrace();
                System.exit(1);
            }
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Atlanta Pet Adoption Consortium");

        jButton1.setText("Return to Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petadoptionconsortium/imagepackage/adopt3.png"))); // NOI18N

        jLabel3.setText("You have successfully added a pet to the database.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(366, 366, 366))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(109, 109, 109)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.EMPLOYEE_MENU;
        PetAdoptionConsortium.changeScreen = true;// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
