/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package petadoptionconsortium;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import static petadoptionconsortium.PetSearch.fromAgeChoice;
import static petadoptionconsortium.PetSearch.toAgeChoice;
import static petadoptionconsortium.PetSearch.breedChoice;
import static petadoptionconsortium.PetSearch.genderChoice;
import static petadoptionconsortium.PetSearch.typeChoice;
import static petadoptionconsortium.PetSearch.zipcodeChoice;
import java.lang.Math.*;

/**
 *
 * @author Doug
 */
public class AddNewPet extends javax.swing.JPanel {

    public static String typeChoice="";
    public static String breedChoice="";
    public static String genderChoice="";
    public static String ageChoice="";
    public static String nameChoice="";
    public static String zipcodeChoice="";
    public static String petID="";
    public static boolean buttonPressed = false;
    private Vector breeds;
    private Vector genders;
    
    public AddNewPet() {
        genders = new Vector();
        genders.addElement("");
        genders.addElement("Male");
        genders.addElement("Female");
        Connection connection = null;
        Statement statement1 = null;
        Statement statement2 = null;
        java.sql.ResultSet catBreedsResultSet = null;
        java.sql.ResultSet dogBreedsResultSet = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection(PetAdoptionConsortium.CONN_STRING,"root","");
            statement1 = connection.createStatement();
            statement2 = connection.createStatement();
            this.breeds = new Vector();
            breeds.addElement("");
            if (AddNewDogOrCat.dogOrCat.equals("Dog")) {
                dogBreedsResultSet = statement1.executeQuery("SELECT breed FROM DogBreed");
                while (dogBreedsResultSet.next()) {
                    this.breeds.addElement(dogBreedsResultSet.getObject(1));
                }
            }
            else if (AddNewDogOrCat.dogOrCat.equals("Cat")) {
                catBreedsResultSet = statement2.executeQuery("SELECT breed FROM CatBreed");
                while (catBreedsResultSet.next()) {
                    this.breeds.addElement(catBreedsResultSet.getObject(1));
                }
            }
        }
        catch(SQLException sqlException) {
            sqlException.printStackTrace();
            System.exit(1);
        }
        catch(ClassNotFoundException classNotFound) {
            classNotFound.printStackTrace();
            System.exit(1);
        }
        finally {
            try {
                statement1.close();
                statement2.close();
                connection.close();
            }
            catch(Exception exception) {
                exception.printStackTrace();
                System.exit(1);
            }
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        breedChoiceComboBox = new javax.swing.JComboBox();
        genderChoiceComboBox = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        nameChoiceTextField = new javax.swing.JTextField();
        ageChoiceTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Atlanta Pet Adoption Consortium");

        jLabel2.setText("Add New Pet for Shelter " + PetAdoptionConsortium.shelterName);

        jLabel4.setText("Breed");

        jLabel5.setText("Gender");

        jLabel6.setText("Age");

        jLabel7.setText("Pet Name");

        breedChoiceComboBox.setModel(new DefaultComboBoxModel(breeds));

        genderChoiceComboBox.setModel(new DefaultComboBoxModel(genders));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Return to Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(submitButton)
                                    .addComponent(genderChoiceComboBox, 0, 156, Short.MAX_VALUE)
                                    .addComponent(breedChoiceComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameChoiceTextField)
                                    .addComponent(ageChoiceTextField))))
                        .addGap(0, 408, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(breedChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(genderChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ageChoiceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nameChoiceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        buttonPressed = true;
        typeChoice = AddNewDogOrCat.dogOrCat;
        breedChoice = breedChoiceComboBox.getSelectedItem().toString();
        genderChoice = genderChoiceComboBox.getSelectedItem().toString();
        ageChoice = ageChoiceTextField.getText();
        nameChoice = nameChoiceTextField.getText();
        petID = ""+(int)(Math.random()*10000);
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.ADD_NEW_PET_SUCCESS;
        PetAdoptionConsortium.changeScreen = true;
    }//GEN-LAST:event_submitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.EMPLOYEE_MENU;
        PetAdoptionConsortium.changeScreen = true;// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageChoiceTextField;
    private javax.swing.JComboBox breedChoiceComboBox;
    private javax.swing.JComboBox genderChoiceComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameChoiceTextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
