/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package petadoptionconsortium;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author Doug
 */
public class AssignFoster extends javax.swing.JPanel {

    /**
     * Creates new form AssignFoster
     */
    public static String fosterPhoneChoice="";
    public static String fosterNameChoice="";
    public static String petIDChoice="";
    private Vector petIDVector;
    private Vector namePhoneVector;
    private int numberOfColumns;
    
    public AssignFoster() {
        
        
        Connection connection = null;
        Statement statement = null;
        java.sql.ResultSet petIDResultSet = null;
        java.sql.ResultSet namePhoneResultSet = null;
        ResultSetMetaData metaData = null;
        ResultSetMetaData namePhoneMetaData = null;
        petIDVector = new Vector();
        namePhoneVector = new Vector();
                
        this.numberOfColumns = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection(PetAdoptionConsortium.CONN_STRING,"root","");
            String petIdQuery = "SELECT PetID FROM Pet WHERE ShelterName = ?";
            PreparedStatement pstatement = connection.prepareStatement(petIdQuery);
            pstatement.setString(1, PetAdoptionConsortium.shelterName);
            petIDResultSet = pstatement.executeQuery();
            while (petIDResultSet.next()) {
                this.petIDVector.addElement(petIDResultSet.getObject(1));
            }
            statement = connection.createStatement();
            namePhoneResultSet = statement.executeQuery("SELECT Pname, Pphone FROM Fosterer");
            namePhoneMetaData = namePhoneResultSet.getMetaData();
            this.numberOfColumns = namePhoneMetaData.getColumnCount();
            while (namePhoneResultSet.next()) {
                Vector newRow = new Vector();
                for(int i = 1; i <= this.numberOfColumns; i++) {
                    newRow.addElement(namePhoneResultSet.getObject(i));
                }
                this.namePhoneVector.addElement(newRow.elementAt(0)+"-"+newRow.elementAt(1));
            }
            
            
            
            
        }
        catch(SQLException sqlException) {
            sqlException.printStackTrace();
            System.exit(1);
        }
        catch(ClassNotFoundException classNotFound) {
            classNotFound.printStackTrace();
            System.exit(1);
        }
        finally {
            try {
                statement.close();
                connection.close();
            }
            catch(Exception exception) {
                exception.printStackTrace();
                System.exit(1);
            }
        }
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        petIDChoiceComboBox = new javax.swing.JComboBox();
        namePhoneChoiceComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();

        jLabel1.setText("Atlanta Pet Adoption Consortium");

        jLabel2.setText("Assign Pet from Shelter " + PetAdoptionConsortium.shelterName);

        petIDChoiceComboBox.setModel(new DefaultComboBoxModel(petIDVector));

        namePhoneChoiceComboBox.setModel(new DefaultComboBoxModel(namePhoneVector));

        jLabel3.setText("PetID");

        jLabel4.setText("Name-Phone");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(petIDChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namePhoneChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(petIDChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(namePhoneChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(submitButton)
                .addContainerGap(351, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        petIDChoice = petIDChoiceComboBox.getSelectedItem().toString();
        String namePhoneChoice = namePhoneChoiceComboBox.getSelectedItem().toString();
        fosterNameChoice = namePhoneChoice.split("-")[0];
        fosterPhoneChoice = namePhoneChoice.split("-")[1];
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.ASSIGN_FOSTER_SUCCESS;
        PetAdoptionConsortium.changeScreen=true;// TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox namePhoneChoiceComboBox;
    private javax.swing.JComboBox petIDChoiceComboBox;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
