/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package petadoptionconsortium;

/**
 *
 * @author Doug
 */
public class PetSearchDogOrCat extends javax.swing.JPanel {

    /**
     * Creates new form PetSearchDogOrCat
     */
    public static String dogOrCat = "Both";
    public PetSearchDogOrCat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dogButton = new javax.swing.JButton();
        catButton = new javax.swing.JButton();
        bothButton = new javax.swing.JButton();

        jLabel1.setText("Atlanta Pet Adoption Consortium");

        dogButton.setText("Search for Dogs");
        dogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogButtonActionPerformed(evt);
            }
        });
        dogButton.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dogButtonAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        catButton.setText("Search for Cats");
        catButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catButtonActionPerformed(evt);
            }
        });

        bothButton.setText("Search for Both!");
        bothButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bothButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(dogButton)
                        .addGap(5, 5, 5)
                        .addComponent(catButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bothButton)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bothButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(383, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogButtonActionPerformed
        dogOrCat = "Dog";// TODO add your handling code here:
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.PET_SEARCH;
        PetAdoptionConsortium.changeScreen = true;
    }//GEN-LAST:event_dogButtonActionPerformed

    private void bothButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bothButtonActionPerformed
        dogOrCat = "Both";// TODO add your handling code here:
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.PET_SEARCH;
        PetAdoptionConsortium.changeScreen = true;
    }//GEN-LAST:event_bothButtonActionPerformed

    private void catButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catButtonActionPerformed
        dogOrCat = "Cat";// TODO add your handling code here:
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.PET_SEARCH;
        PetAdoptionConsortium.changeScreen = true;
    }//GEN-LAST:event_catButtonActionPerformed

    private void dogButtonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dogButtonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_dogButtonAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bothButton;
    private javax.swing.JButton catButton;
    private javax.swing.JButton dogButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
