/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package petadoptionconsortium;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import java.util.Vector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Doug
 */
public class PetSearch extends javax.swing.JPanel {

    /**
     * Creates new form PetSearch
     */
    public static String typeChoice="";
    public static String breedChoice="";
    public static String genderChoice="";
    public static String fromAgeChoice="";
    public static String toAgeChoice="";
    public static String zipcodeChoice="";
    public static Vector breeds;
    private Vector genders;
    private Vector ages1;
    private Vector ages2;
    public PetSearch() {
        genders = new Vector();
        genders.addElement("");
        genders.addElement("Male");
        genders.addElement("Female");
        ages1 = new Vector();
        ages2 = new Vector();
        ages1.addElement("");
        ages2.addElement("");
        for (int i = 0; i < PetAdoptionConsortium.MAX_AGE; i++) {
            ages1.addElement(""+i);
            ages2.addElement(""+i);
        }
        Connection connection = null;
        Statement statement1 = null;
        Statement statement2 = null;
        java.sql.ResultSet catBreedsResultSet = null;
        java.sql.ResultSet dogBreedsResultSet = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection(PetAdoptionConsortium.CONN_STRING,"root","");
            statement1 = connection.createStatement();
            statement2 = connection.createStatement();
            this.breeds = new Vector();
            breeds.addElement("");
            if (PetSearchDogOrCat.dogOrCat.equals("Dog")) {
                dogBreedsResultSet = statement1.executeQuery("SELECT breed FROM DogBreed");
                while (dogBreedsResultSet.next()) {
                    this.breeds.addElement(dogBreedsResultSet.getObject(1));
                }
            }
            else if (PetSearchDogOrCat.dogOrCat.equals("Cat")) {
                catBreedsResultSet = statement2.executeQuery("SELECT breed FROM CatBreed");
                while (catBreedsResultSet.next()) {
                    this.breeds.addElement(catBreedsResultSet.getObject(1));
                }
            }
            else if (PetSearchDogOrCat.dogOrCat.equals("Both")) {
                dogBreedsResultSet = statement1.executeQuery("SELECT breed FROM DogBreed");
                catBreedsResultSet = statement2.executeQuery("SELECT breed FROM CatBreed");
                while (dogBreedsResultSet.next()) {
                    this.breeds.addElement(dogBreedsResultSet.getObject(1));
                }
                while (catBreedsResultSet.next()) {
                    this.breeds.addElement(catBreedsResultSet.getObject(1));
                }
            }
        }
        catch(SQLException sqlException) {
            sqlException.printStackTrace();
            System.exit(1);
        }
        catch(ClassNotFoundException classNotFound) {
            classNotFound.printStackTrace();
            System.exit(1);
        }
        finally {
            try {
                statement1.close();
                statement2.close();
                connection.close();
            }
            catch(Exception exception) {
                exception.printStackTrace();
                System.exit(1);
            }
        }
        
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        zipcodeChoiceTextField = new javax.swing.JTextField();
        breedChoiceComboBox = new javax.swing.JComboBox();
        genderChoiceComboBox = new javax.swing.JComboBox();
        fromAgeChoiceComboBox = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        toAgeChoiceComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Atlanta Pet Adoption Consortium");

        jLabel2.setText("Pet Search");

        jLabel3.setText("Zipcode");

        jLabel5.setText("Breed");

        jLabel6.setText("Gender");

        jLabel7.setText("Age");

        zipcodeChoiceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeChoiceTextFieldActionPerformed(evt);
            }
        });

        breedChoiceComboBox.setModel(new DefaultComboBoxModel(breeds));

        genderChoiceComboBox.setModel(new DefaultComboBoxModel(genders));

        fromAgeChoiceComboBox.setModel(new DefaultComboBoxModel(ages1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Return to Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("From");

        jLabel10.setText("To");

        toAgeChoiceComboBox.setModel(new DefaultComboBoxModel(ages2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(zipcodeChoiceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(breedChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fromAgeChoiceComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(toAgeChoiceComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(submitButton)))
                    .addComponent(jLabel1))
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(zipcodeChoiceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(breedChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(genderChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fromAgeChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(toAgeChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zipcodeChoiceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeChoiceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeChoiceTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.GUEST_MENU;// TODO add your handling code here:
        PetAdoptionConsortium.changeScreen = true;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        typeChoice = PetSearchDogOrCat.dogOrCat;
        breedChoice = breedChoiceComboBox.getSelectedItem().toString();
        genderChoice = genderChoiceComboBox.getSelectedItem().toString();
        fromAgeChoice = fromAgeChoiceComboBox.getSelectedItem().toString();
        toAgeChoice = toAgeChoiceComboBox.getSelectedItem().toString();
        zipcodeChoice = zipcodeChoiceTextField.getText();
        PetAdoptionConsortium.currentScreen = PetAdoptionConsortium.PET_SEARCH_RESULTS;
        PetAdoptionConsortium.changeScreen = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox breedChoiceComboBox;
    private javax.swing.JComboBox fromAgeChoiceComboBox;
    private javax.swing.JComboBox genderChoiceComboBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox toAgeChoiceComboBox;
    private javax.swing.JTextField zipcodeChoiceTextField;
    // End of variables declaration//GEN-END:variables
}
